apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::304572964859:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-138KEY8HNN79I
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::304572964859:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-29T17:57:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "919"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c206d53d-71e6-11ea-ad0f-0ae3684b3b18
